apiVersion: run.ai/v2alpha1
kind: InteractiveWorkload
metadata:
  name: &name jupyter-cpu
  namespace: runai-studentmichele-juraj
spec:
  cpu:
    value: "8"
  preemptible:
    value: true
  image:
    value: jjurm/runai-python-job
  name:
    value: *name
  nodeType:
    value: "CPU"
  username:
    value: jmicko@student.ethz.ch
  workingDir:
    value: /mydata/studentmichele/juraj
  environment:
    items:
      HOME:
        value: /workdir
      ENV_FILE:
        value: /myhome/.env
